app = "rustdht-signaling"
primary_region = "ord"

[build]

[env]
  RUST_LOG = "info"

# HTTP service (required for health checks)
[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

# UDP service for WebRTC signaling
[[services]]
  protocol = "udp"
  internal_port = 9090
  
  [[services.ports]]
    port = 9090

# TCP service for HTTP health checks
[[services]]
  protocol = "tcp"
  internal_port = 8080
  
  [[services.ports]]
    port = 8080

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "512mb"

# Ensure we get an IPv4 address
[experimental]
  auto_rollback = true