app = "rustdht-signaling"
primary_region = "ord"

[build]

[env]
  RUST_LOG = "info"

# UDP service for WebRTC signaling
[[services]]
  protocol = "udp"
  internal_port = 9090
  
  [[services.ports]]
    port = 9090

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"